### PR TITLE
Custom main page caption from template

### PR DESCRIPTION
**Pull request by rica-carv**
Enable template based custom main page caption and some code change.

### CODE REVIEW

**Comment by Jimmi08** [comment]
Are you sure that this is correct way?  It looks like something is missing after ?
`$caption = ($template['LINK_MAIN_CAPTION']?:LAN_LINKS_30);`

I understand what you changed with navigators. But you should change other parts of code too, not just category function. It was coded this way to easy replace navigator by shortcodes.

**Comment by rica-carv** [comment]
`$template['LINK_MAIN_CAPTION']?:LAN_LINKS_30`
[It's the ternary shorthand of if, and it's only usable after PHP 5.2](http://stackoverflow.com/questions/6277222/php-shorthand-ternary-operator-parse-error-unexpected)
Before we had to use `$template['LINK_MAIN_CAPTION']?$template['LINK_MAIN_CAPTION']:LAN_LINKS_30`

**Comment by Jimmi08** [comment]
Thanks. Not considered as improvement, hard to undestand. 

Sometimes in future. It's used in more functions that in this one.  You need to set something in prefs to have it . I didn't test it lately. 

I use 2.3.2 version. You can see it here:
http://www.e107.sk/links_page/links/cat
- first two panels are displayNavigator('cat'),  third is displaySortOrder('cat');     
Set it in prefs on Category page.

**Comment by rica-carv** [comment]
Not a problem.
Since the core e107 minimum requirements is already PHP 5.3 or higher, there's no need to keep old deprecated code...

I personally don't like your navigator, i liked the dropdown legacy one, but hey, that's the future and i got to live with it. 😉 
Further more i won't need it on the main links page, since i have the menu (which also has it) permanently shown on every page.
Anyway, as some more enhancement, a suggestion: ~~create a shortcode and make those both navigators rendered from the template~~.
Update: [the shortcode already exists](https://github.com/Jimmi08/links_page/blob/6956a0bab4ff92ce7a540dbb014a18b568eb8524/links_page_shortcodes.php#L379), so it's just a matter of transfering the code and when calls are used from code, call it directly or call it via template (a approach that Cameron doesn't like too much. 😄 )...

**Comment by Jimmi08** [comment]
You could fork this and create your own version. I needed to solve links, but I have no plans to improve this.

**Comment by rica-carv** [comment]
I've already forked it, that's from where i'm submitting this changes.

Anyway, i'm planning some small improvements, nothing more, so i think that all could be together, instead of having n versions of the same plugin, don't you think?
As long the alterations don't mess up who's using it...

**Pull request merged**
