### PR TITLE
Some corrections

### PR DESCRIPTION
**Pull request by yesszus**

### CODE REVIEW

**Comment by Jimmi08** [comment]
Hi, why did you change col-md-1 to col-md-2? (Sum is not 12 colums)  It's not correct.  I will change it to back in next pull. Otherwise great work.

**Comment by yesszus** [comment]
Original col-md-1 : 

links

After changed col-md-2 : 

links2

**Comment by Jimmi08** [comment]
Yes, but you should change first column too to 7.  Or maybe I am just summing wrong way. I will look at it, don't have access to source now.
But I think if you enable comments, it will get broken. 
Is your site out? Could you give me the link? 
And I would like to know your opinion about language folder. There are no subfolders for languages now (f.e. not English folder). I dislike it, but I can change it. I just didn't need it before.

**Comment by yesszus** [comment]
I will change it to back in original col-md-1.
See lang folder: https://github.com/yesszus/links_page/tree/master/languages

**Comment by Jimmi08** [comment]
I think that this is better structure:
image

By the way, do you know how to use e107 language functionality for non core plugin?  One line of code and you can add this plugin to it too. Because I am cleaning strings, it's helpfull.

**Pull request merged**
