### PR TITLE
Enable use of core shortcodes inside template

### PR DESCRIPTION
**Pull request by rica-carv**
Change to enable parsing of core shortcodes inside the template, ie like {GLYPH}

### CODE REVIEW

**Comment by rica-carv** [comment]
@Jimmi08 If possible, test my changes to see if i don't mess up anything...
Thanks...

**Comment by Jimmi08** [comment]
I will do it in some time (In January, not soon). There is stable version, people should use that one. Don't worry.

**Comment by rica-carv** [comment]
Ok, thanks. Sorry for all this trouble...

P.S.: Got some more coming, not soon, but it will happen near... 😉

**Comment by Jimmi08** [comment]
You are welcome. It's nice to know that there is somebody who really use this.

**Comment by rica-carv** [comment]
😄 Yes, i do, and i will keep using it, for sure...

**Pull request merged**
